### ISSUE TITLE
More Features

### ISSUE THREAD

**Issue by Fair-Tech** [TheLtWilson/wave-link-audio-wrapper#1]
This is awesome! I'm wondering, where did you get the information on what to send to the websocket for commands? 

I really want to be able to toggle between 2 devices for Monitor Mix with a Hotkey, or preferably programmatically with my audio manager. 
Is there any way you could add this feature? Along with being able to adjust the levels of each audio input, this would basically be like a Stream Deck replacement.

**Comment by TheLtWilson** [comment]
While you will have to modify the script yourself to handle switching between two sources with one hotkey, **I have provided the new `change_output_device(identifier, name)` function as of the latest commit (58fc274).**

You can figure out the identifier and names of all your available devices by checking the `latest.log` file. It should show your available outputs as well as the one that Wave Link currently has selected.

Hope this helps you with your use case.

**As for how** I figured what websocket commands to send, I actually just used the Stream Deck. There's a key you can add in the registry editor ([see instructions](https://imgur.com/a/6eTOaO5)) that allows you to debug Stream Deck plugins. From there I found the websocket connection while monitoring network activity in the Wave Link plugin. Then I just pressed buttons on my Stream Deck to see what commands it sent.
